Add angular support
formkit/auto-animate pull request #38
Opened 2022-06-14 13:16 UTC by Waterstraal

Adds an auto-animate Angular directive 

Closes #19

2022-06-14 13:40 UTC, danielehrhardt approved these changes

2022-06-14 14:21 UTC, justin-schroeder requested changes
Overall this looks great — my only immediate feedback here is to use a unique example for the angular section. One of our objectives is to always use unique examples on the docs page.

2022-06-15 07:49 UTC, Waterstraal commented on docs/src/examples/angular/ActualAngularApp.vue
> +import { vAutoAnimate } from "../../../../src/index"
Any idea? 

I have no Vue experience, and the examples are coded in Vue, so please let's think of something simple :)

2022-06-15 11:05 UTC, Waterstraal commented on docs/src/examples/angular/ActualAngularApp.vue
> +import { vAutoAnimate } from "../../../../src/index"
Updated the example

2022-06-15 13:46 UTC, merged